# Generated by Django 5.1.3 on 2024-12-05 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_producto', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=30)),
                ('fecha_ingreso', models.DateField()),
                ('precio_producto', models.PositiveBigIntegerField()),
                ('descripcion_producto', models.CharField(max_length=20)),
                ('categoria_producto', models.CharField(max_length=20)),
                ('stock', models.PositiveIntegerField()),
            ],
        ),
    ]
