# Generated by Django 5.1 on 2024-12-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id_venta', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('id_cliente', models.PositiveIntegerField()),
                ('fecha_venta', models.DateField()),
                ('total_venta', models.DecimalField(decimal_places=2, max_digits=6)),
                ('id_producto', models.PositiveIntegerField()),
                ('id_empleado', models.PositiveIntegerField()),
                ('cantidad_productos', models.PositiveIntegerField()),
            ],
        ),
    ]
