# Generated by Django 5.1.3 on 2024-12-05 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id_proveedor', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(max_length=20)),
                ('telefono_proveedor', models.PositiveBigIntegerField()),
                ('correo_electronico', models.EmailField(max_length=20)),
                ('direccion', models.CharField(max_length=20)),
                ('contacto_principal', models.CharField(max_length=10)),
            ],
        ),
    ]
